import {
  Activity,
  Banknote,
  BarChart3,
  Bell,
  CalendarCheck,
  Camera,
  CheckCheck,
  Clock,
  Database,
  FileBarChart,
  Filter,
  FolderKanban,
  Gauge,
  Globe,
  Headset,
  HeartPulse,
  KeyRound,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Network,
  Plane,
  Plug,
  Receipt,
  RefreshCw,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Timer,
  TriangleAlert,
  UserPlus,
  Users,
  Wallet,
  Webhook,
} from "lucide-react";
import type { ProductPageData } from "./product-page";

export const PRODUCT_CONTENT: Record<string, ProductPageData> = {
  "time-tracking": {
    slug: "time-tracking",
    eyebrow: "Time Tracking",
    icon: Clock,
    heroAnim: "timer",
    title: "Effortless time. Payroll-ready timesheets.",
    lede: "Capture every minute with a one-tap, idle-aware timer across web, desktop, and mobile — then let WorkPulse reconcile entries into approval-ready, billable-classified timesheets with payroll-grade rounding.",
    problem: {
      heading: "Manual timesheets leak hours — and trust.",
      body: "Spreadsheet timesheets get reconstructed from memory days later, double-count idle time, and quietly drop billable work. Finance can't trust the totals and disputes erode morale. WorkPulse captures time at the source and reconciles it automatically.",
    },
    capabilities: [
      { icon: Timer, title: "One-tap, idle-aware timer", body: "Start and switch tasks in a tap on web, desktop, and mobile. Idle-threshold detection prompts to discard or reassign inactive time." },
      { icon: ListChecks, title: "Automatic timesheet reconciliation", body: "Raw entries roll up into daily and weekly timesheets — deduplicated, normalized, and ready for approval with no manual assembly." },
      { icon: Banknote, title: "Billable vs. non-billable allocation", body: "Tag projects and tasks as billable or internal; allocations flow straight into invoicing and payroll exports." },
      { icon: Gauge, title: "Payroll-grade rounding rules", body: "Configurable rounding (nearest 1 / 5 / 15 min), overtime thresholds, and break policies applied consistently org-wide." },
      { icon: CheckCheck, title: "Approvals & corrections", body: "Multi-step approval chains with audit-tracked corrections — approve, reject, or request changes from one queue." },
      { icon: Webhook, title: "API-first time entries", body: "Push and pull entries via REST API and webhooks to sync with your PSA, ERP, or data warehouse." },
    ],
    gallery: [
      {
        src: "/timesheet.png",
        title: "Weekly team timesheets, at a glance",
        body: "Review every employee's Mon–Sun hours and weekly totals, filter by Employees or Projects and by status (Approved / Pending / Flagged), search by team or EID, and approve in bulk — 3,630:11 reconciled in a single grid.",
      },
      {
        src: "/dailytime.png",
        title: "Drill into any single day",
        body: "Open a day to see working vs. non-working time, activity %, and billable hours — plus the exact tasks and projects behind the numbers, with approval status front and center.",
      },
      {
        src: "/weeklytime.png",
        title: "A full week of activity per person",
        body: "Hours-per-day working vs. non-working bars, total working and billable time, average activity, and overall progress — the weekly view managers approve from.",
      },
    ],
    how: {
      heading: "From keystroke to payroll, automatically.",
      steps: [
        { title: "Capture", body: "The timer — or the lightweight desktop agent — records start/stop events and idle intervals per task, timezone- and DST-aware." },
        { title: "Reconcile", body: "Entries are normalized, rounded per policy, deduplicated, and classified billable / non-billable into a draft timesheet." },
        { title: "Approve & export", body: "Managers approve through the chain; approved hours export to payroll and invoicing as CSV / PDF or via the API." },
      ],
    },
    specs: [
      { label: "Platforms", value: "Web · Desktop · Mobile" },
      { label: "Rounding", value: "1 / 5 / 15-minute, configurable" },
      { label: "Idle detection", value: "Threshold-based, per policy" },
      { label: "Export", value: "CSV · PDF · REST API" },
      { label: "Approvals", value: "Multi-step, audit-logged" },
      { label: "Timezone", value: "Per-user, DST-aware" },
    ],
    related: ["attendance", "payroll", "projects"],
    faqs: [
      { q: "Does it track idle time?", a: "Yes — idle-threshold detection flags inactivity beyond a configurable limit and prompts the user to discard or reassign it, so timesheets reflect real work." },
      { q: "Can hours flow into payroll?", a: "Approved hours export with payroll-grade rounding and overtime rules as CSV / PDF, or through the REST API to your provider." },
      { q: "Is there an offline mode?", a: "The desktop agent buffers entries offline and syncs on reconnect — no time is lost." },
    ],
    cta: { title: "Stop reconstructing timesheets.", body: "Capture time at the source and ship payroll-ready hours in minutes." },
  },

  "activity-monitoring": {
    slug: "activity-monitoring",
    eyebrow: "Activity & Productivity",
    icon: Activity,
    title: "Productivity analytics with consent — not surveillance theatre.",
    lede: "Measure active vs. idle time, application and URL usage, and a per-person productivity score from sampled activity signals — with consent-aware capture and PII redaction built in.",
    problem: {
      heading: "You can't improve what you can't see — responsibly.",
      body: "Leaders lack visibility into where focus actually goes, while heavy-handed monitoring destroys trust. WorkPulse surfaces aggregate, consent-aware signals that inform coaching, not punishment.",
    },
    capabilities: [
      { icon: Activity, title: "Active vs. idle analysis", body: "Activity sampling distinguishes active engagement from idle time — without keystroke logging by default." },
      { icon: Globe, title: "App & URL classification", body: "A configurable taxonomy classifies applications and domains as productive, neutral, or distracting per role." },
      { icon: Gauge, title: "Productivity scoring model", body: "A transparent, weighted model rolls usage into per-person and per-team productivity indices." },
      { icon: Camera, title: "Screenshot capture (optional)", body: "Policy-gated screenshots at configurable intervals, with blur, on/off controls, and full audit trails." },
      { icon: ShieldCheck, title: "Consent-aware & PII redaction", body: "Capture respects consent settings; private-mode windows and sensitive fields are redacted at the source." },
      { icon: Filter, title: "Configurable thresholds", body: "Tune idle limits, capture frequency, and classification rules org-wide or per team." },
    ],
    how: {
      heading: "Signals in, insight out — privacy preserved.",
      steps: [
        { title: "Sample", body: "The agent samples foreground app / URL and activity state at intervals; private mode and excluded apps are never captured." },
        { title: "Classify & score", body: "Signals are classified against your taxonomy and weighted into productivity scores; PII is redacted at capture." },
        { title: "Surface", body: "Heatmaps, app / URL breakdowns, and scores appear in Insights — aggregate by default, drill-down when authorized." },
      ],
    },
    specs: [
      { label: "Capture", value: "Interval activity sampling" },
      { label: "Classification", value: "Configurable app/URL taxonomy" },
      { label: "Screenshots", value: "Optional · blurred · gated" },
      { label: "Privacy", value: "Consent-aware · PII redaction" },
      { label: "Retention", value: "Configurable, 3–36 months" },
      { label: "Access", value: "RBAC, aggregate-first" },
    ],
    related: ["time-tracking", "ai-insights", "security"],
    faqs: [
      { q: "Is this surveillance?", a: "No. Capture is consent-aware, aggregate-first, and PII-redacted, with screenshots optional and policy-gated. It is built to inform coaching, not to spy." },
      { q: "Are keystrokes logged?", a: "Keystroke content is not logged by default; activity is inferred from sampled input presence, not contents." },
      { q: "Who can see the data?", a: "Access is RBAC-gated — most roles see aggregates, with drill-down reserved for authorized roles and recorded in audit logs." },
    ],
    cta: { title: "See focus clearly — and fairly.", body: "Turn raw activity into productivity insight your teams can trust." },
  },

  projects: {
    slug: "projects",
    eyebrow: "Project & Task Management",
    icon: FolderKanban,
    title: "Plan, assign, and ship — with capacity and budget in view.",
    lede: "Kanban boards with WIP limits, task dependencies, capacity planning, and budget-vs-actual tracking that sits right next to your time and activity data.",
    problem: {
      heading: "Delivery slips when capacity and time live in different tools.",
      body: "Project plans drift from reality when hours, capacity, and progress are scattered across tools. WorkPulse keeps delivery, capacity, and time in one model, so overruns surface early enough to act.",
    },
    capabilities: [
      { icon: FolderKanban, title: "Kanban with WIP limits", body: "Column-based boards enforce work-in-progress limits to expose bottlenecks and protect flow." },
      { icon: ListChecks, title: "Tasks, subtasks & dependencies", body: "Model dependencies and blockers; critical-path shifts become visible before they bite." },
      { icon: Gauge, title: "Capacity planning", body: "Allocate people against availability; over-allocation is flagged against tracked hours." },
      { icon: BarChart3, title: "Budget vs. actual", body: "Track budgeted hours and cost against real tracked time — burn rate and variance in real time." },
      { icon: Users, title: "Roles, leads & teams", body: "Assign leads and managers; team panels show who is on what at a glance." },
      { icon: FileBarChart, title: "Delivery reporting", body: "Burn-down, completion, and throughput reports export to PDF / CSV or your warehouse." },
    ],
    how: {
      heading: "One model for plan, people, and progress.",
      steps: [
        { title: "Plan", body: "Create projects, set budgets and deadlines, and break work into tasks with owners and dependencies." },
        { title: "Execute", body: "Teams move cards across the board; tracked time attaches to tasks automatically." },
        { title: "Steer", body: "Capacity, burn rate, and variance update live — reallocate before deadlines slip." },
      ],
    },
    specs: [
      { label: "Boards", value: "Kanban, WIP-limited" },
      { label: "Dependencies", value: "Task & subtask" },
      { label: "Capacity", value: "Availability-based" },
      { label: "Budgets", value: "Hours & cost · variance" },
      { label: "Reports", value: "Burn-down · throughput" },
      { label: "Export", value: "PDF · CSV · API" },
    ],
    related: ["time-tracking", "workforce", "reports"],
    faqs: [
      { q: "Does tracked time attach to tasks?", a: "Yes — time entries link to tasks and projects, so budget-vs-actual and capacity are always grounded in real hours." },
      { q: "Can I see who's over-allocated?", a: "Capacity planning flags over-allocation against availability and tracked time before it causes burnout or slippage." },
      { q: "Is there a 'My tasks' view?", a: "Each member gets a personal task view across all projects, alongside the per-project boards." },
    ],
    cta: { title: "Ship on time, with eyes open.", body: "Keep delivery, capacity, and time in one connected model." },
  },

  attendance: {
    slug: "attendance",
    eyebrow: "Attendance & Scheduling",
    icon: CalendarCheck,
    title: "Attendance, shifts, and leave — adherent and audit-ready.",
    lede: "Geofenced clock-in, shift scheduling, leave accrual, and attendance-exception handling that reconcile against tracked time and feed payroll clean.",
    problem: {
      heading: "Shift adherence and leave are a spreadsheet nightmare.",
      body: "Manual attendance and leave tracking create disputes, buddy-punching, and payroll errors. WorkPulse captures attendance at the source and reconciles exceptions automatically.",
    },
    capabilities: [
      { icon: MapPin, title: "Geofenced clock-in", body: "Location-aware clock-in for field and on-site teams prevents off-site or proxy punching." },
      { icon: CalendarCheck, title: "Shift scheduling", body: "Build rosters and shift patterns, publish schedules, and track adherence." },
      { icon: Clock, title: "Attendance exceptions", body: "Late, early, and missed punches are flagged as exceptions for one-click resolution." },
      { icon: Plane, title: "Leave & accrual", body: "Configurable leave types with accrual rules, live balances, and approval workflows." },
      { icon: CheckCheck, title: "Approval workflows", body: "Leave and correction requests route through multi-step, audit-logged approvals." },
      { icon: Wallet, title: "Payroll reconciliation", body: "Attendance reconciles against tracked hours and exports clean to payroll." },
    ],
    how: {
      heading: "Capture, reconcile, approve.",
      steps: [
        { title: "Clock in", body: "Members clock in via web, mobile, or geofence; the system records timestamp, location, and shift." },
        { title: "Reconcile", body: "Punches reconcile against schedules and tracked time; exceptions surface automatically." },
        { title: "Approve & pay", body: "Managers clear exceptions and leave; clean attendance flows straight to payroll." },
      ],
    },
    specs: [
      { label: "Clock-in", value: "Web · Mobile · Geofenced" },
      { label: "Scheduling", value: "Shift patterns & rosters" },
      { label: "Leave", value: "Accrual-based, configurable" },
      { label: "Exceptions", value: "Auto-flagged" },
      { label: "Approvals", value: "Multi-step, audit-logged" },
      { label: "Export", value: "Payroll-ready CSV / PDF" },
    ],
    related: ["time-tracking", "payroll", "workforce"],
    faqs: [
      { q: "Does it prevent buddy-punching?", a: "Geofenced and device-aware clock-in ties attendance to location and identity, eliminating off-site and proxy punches." },
      { q: "How is leave handled?", a: "Configurable leave types with accrual rules, live balances, and approval chains; balances reconcile into payroll." },
      { q: "Does it support shifts across timezones?", a: "Yes — schedules and punches are timezone- and DST-aware." },
    ],
    cta: { title: "End attendance disputes.", body: "Capture attendance at the source and reconcile it automatically." },
  },

  workforce: {
    slug: "workforce",
    eyebrow: "Workforce Management",
    icon: Users,
    title: "A single source of truth for your people and org structure.",
    lede: "Employee directory and profiles, org hierarchy, role-based access, and lifecycle management from invite to offboard — with headcount analytics built in.",
    problem: {
      heading: "People data is fragmented across HR, IT, and ops.",
      body: "When the org chart, access, and productivity data live in separate systems, onboarding lags and access drifts. WorkPulse unifies the workforce record with access and activity in one place.",
    },
    capabilities: [
      { icon: Users, title: "Directory & profiles", body: "Rich profiles with role, department, team, contact, and productivity context in one view." },
      { icon: Network, title: "Org hierarchy", body: "Model departments, teams, and reporting lines that drive access and rollups." },
      { icon: KeyRound, title: "Role-based access (RBAC)", body: "Least-privilege roles control exactly what each person can see and do." },
      { icon: UserPlus, title: "Lifecycle management", body: "Invite → active → suspend → offboard, with status reflected everywhere instantly." },
      { icon: BarChart3, title: "Headcount analytics", body: "Track headcount, distribution, and productivity by department and team." },
      { icon: Mail, title: "Bulk invites & provisioning", body: "Invite by email or link, with CSV import and SCIM 2.0 provisioning from your IdP." },
    ],
    how: {
      heading: "One record, many systems.",
      steps: [
        { title: "Provision", body: "Create or sync people via invite, CSV, or SCIM; roles and teams assign on entry." },
        { title: "Operate", body: "Profiles connect to time, attendance, and activity; access follows the org model." },
        { title: "Offboard", body: "Suspend or remove access in one action; the audit trail captures every change." },
      ],
    },
    specs: [
      { label: "Directory", value: "Profiles + org hierarchy" },
      { label: "Access", value: "RBAC, least-privilege" },
      { label: "Provisioning", value: "Invite · CSV · SCIM 2.0" },
      { label: "Lifecycle", value: "Invite → offboard" },
      { label: "Analytics", value: "Headcount & distribution" },
      { label: "Audit", value: "All changes logged" },
    ],
    related: ["security", "attendance", "payroll"],
    faqs: [
      { q: "Can I sync from my IdP?", a: "Yes — SCIM 2.0 provisioning keeps users and groups in sync with your identity provider." },
      { q: "How granular is access control?", a: "RBAC assigns least-privilege permissions per module and action; custom roles are fully supported." },
      { q: "What happens on offboarding?", a: "A single action suspends or removes access across every module, recorded in the audit log." },
    ],
    cta: { title: "Unify your workforce record.", body: "Bring people, access, and productivity into one source of truth." },
  },

  payroll: {
    slug: "payroll",
    eyebrow: "Payroll & Billing",
    icon: Wallet,
    title: "From tracked hours to pay run — clean, configurable, GL-ready.",
    lede: "Multi-currency pay periods, rate cards, overtime rules, and CSV / PDF exports that turn approved time and attendance into a payroll-ready, GL-mappable output.",
    problem: {
      heading: "Payroll prep means re-keying hours and praying.",
      body: "Exporting from one tool and re-keying into payroll invites errors and delays. WorkPulse turns approved hours and attendance into a clean, auditable pay run.",
    },
    capabilities: [
      { icon: RefreshCw, title: "Pay-period cycles", body: "Weekly, bi-weekly, semi-monthly, or monthly cycles with cutoffs and period locks." },
      { icon: Receipt, title: "Rate cards & overtime", body: "Per-person and per-role rates with overtime, holiday, and shift-differential rules." },
      { icon: Globe, title: "Multi-currency", body: "Bill and pay across currencies with per-entity defaults." },
      { icon: FileBarChart, title: "GL-ready exports", body: "Structured CSV / PDF mapped to your general ledger and payroll provider." },
      { icon: Wallet, title: "Seat-based billing", body: "Per-active-seat subscription billing with proration and add-ons." },
      { icon: ShieldCheck, title: "Audit-ready", body: "Every pay run ties back to approved, audit-logged time and attendance." },
    ],
    how: {
      heading: "Approved hours in, pay run out.",
      steps: [
        { title: "Collect", body: "Approved time, attendance, and leave aggregate by pay period and entity." },
        { title: "Apply rules", body: "Rate cards, overtime, and rounding apply per policy; totals compute by person." },
        { title: "Export", body: "A GL-mapped, multi-currency pay run exports as CSV / PDF or via API to your provider." },
      ],
    },
    specs: [
      { label: "Cycles", value: "Weekly → monthly" },
      { label: "Currency", value: "Multi-currency" },
      { label: "Rates", value: "Per-person/role · OT" },
      { label: "Export", value: "GL-ready CSV/PDF · API" },
      { label: "Billing", value: "Per active seat" },
      { label: "Audit", value: "Traceable to approvals" },
    ],
    related: ["time-tracking", "attendance", "reports"],
    faqs: [
      { q: "Does it integrate with payroll providers?", a: "Exports are GL-mapped CSV / PDF, and the REST API pushes pay runs to common providers." },
      { q: "Is it multi-currency?", a: "Yes — per-entity currency defaults let you bill and pay across regions." },
      { q: "How is overtime handled?", a: "Configurable overtime, holiday, and differential rules apply automatically from approved hours." },
    ],
    cta: { title: "Run payroll without re-keying.", body: "Turn approved hours into a clean, GL-ready pay run." },
  },

  reports: {
    slug: "reports",
    eyebrow: "Reports & Analytics",
    icon: BarChart3,
    title: "Configurable dashboards and scheduled exports — warehouse-ready.",
    lede: "Build role-based dashboards, schedule report delivery, drill from org to individual, and stream data to your BI stack or warehouse.",
    problem: {
      heading: "Decisions wait on someone exporting a spreadsheet.",
      body: "When insight requires manual exports, decisions lag and numbers diverge. WorkPulse delivers live, role-based analytics and pipes the raw data to your BI layer.",
    },
    capabilities: [
      { icon: LayoutDashboard, title: "Configurable dashboards", body: "Drag-and-arrange widgets per role; each person sees the metrics they own." },
      { icon: LineChart, title: "Drill-down analytics", body: "Move from organization to team to individual without leaving the view." },
      { icon: Clock, title: "Scheduled delivery", body: "Schedule recurring reports to inboxes as PDF / CSV on your cadence." },
      { icon: Database, title: "Warehouse export", body: "Stream normalized data to your warehouse or BI tool via API and webhooks." },
      { icon: FileBarChart, title: "Prebuilt report packs", body: "Productivity, time, project, and AI reports available out of the box." },
      { icon: Filter, title: "Filters & segments", body: "Slice by department, team, project, or date — with saved segments." },
    ],
    how: {
      heading: "Live insight, piped where you need it.",
      steps: [
        { title: "Compose", body: "Assemble dashboards from widgets; pin the views each role cares about." },
        { title: "Schedule", body: "Set recurring exports and delivery to stakeholders automatically." },
        { title: "Integrate", body: "Push normalized datasets to your warehouse for blended, company-wide analysis." },
      ],
    },
    specs: [
      { label: "Dashboards", value: "Role-based, configurable" },
      { label: "Drill-down", value: "Org → team → individual" },
      { label: "Delivery", value: "Scheduled PDF / CSV" },
      { label: "Export", value: "API · webhooks · warehouse" },
      { label: "Report packs", value: "Productivity · time · project" },
      { label: "Filters", value: "Saved segments" },
    ],
    related: ["ai-insights", "time-tracking", "activity-monitoring"],
    faqs: [
      { q: "Can I send data to our BI tool?", a: "Yes — normalized datasets stream to your warehouse or BI stack via REST API and webhooks." },
      { q: "Are reports schedulable?", a: "Schedule recurring PDF / CSV delivery to any stakeholder on a daily, weekly, or monthly cadence." },
      { q: "Can dashboards differ by role?", a: "Each role gets its own configurable dashboard, gated by RBAC." },
    ],
    cta: { title: "Stop exporting spreadsheets by hand.", body: "Get live, role-based analytics — and pipe the raw data to your BI stack." },
  },

  "ai-insights": {
    slug: "ai-insights",
    eyebrow: "AI Insights",
    icon: Sparkles,
    title: "Anomaly and burnout detection that flags risk before it costs you.",
    lede: "Trend inference, anomaly detection, and natural-language summaries surface burnout risk, overtime drift, and the people who need attention — automatically.",
    problem: {
      heading: "By the time a problem shows in a report, it's already cost you.",
      body: "Burnout, overtime drift, and disengagement build quietly across thousands of data points. WorkPulse's models surface the signals early, in plain language a manager can act on.",
    },
    capabilities: [
      { icon: Sparkles, title: "Natural-language summaries", body: "Per-person and per-team summaries explain what changed and why, in plain English." },
      { icon: TriangleAlert, title: "Anomaly detection", body: "Statistical models flag deviations in hours, activity, and output against learned baselines." },
      { icon: HeartPulse, title: "Burnout & overtime risk", body: "Sustained overtime and after-hours patterns raise early burnout-risk signals." },
      { icon: LineChart, title: "Trend inference", body: "Detect rising and falling trends over rolling windows versus prior periods." },
      { icon: Users, title: "People who need attention", body: "A ranked, explainable list of who to check in with — and why." },
      { icon: ShieldCheck, title: "Explainable & gated", body: "Every signal cites its evidence; access is RBAC-gated and audit-logged." },
    ],
    how: {
      heading: "From thousands of signals to a short, honest list.",
      steps: [
        { title: "Ingest", body: "Time, attendance, and activity signals feed the models continuously." },
        { title: "Detect", body: "Anomaly and trend models compare against per-person baselines and prior periods." },
        { title: "Explain", body: "Findings surface as ranked, evidence-cited summaries and recommendations." },
      ],
    },
    specs: [
      { label: "Models", value: "Anomaly + trend inference" },
      { label: "Signals", value: "Time · attendance · activity" },
      { label: "Output", value: "NL summaries + ranked risk" },
      { label: "Explainability", value: "Evidence-cited" },
      { label: "Access", value: "RBAC, audit-logged" },
      { label: "Cadence", value: "Continuous" },
    ],
    related: ["activity-monitoring", "reports", "time-tracking"],
    faqs: [
      { q: "Is the AI a black box?", a: "No — every signal cites the underlying evidence, and access is RBAC-gated and recorded in audit logs." },
      { q: "What does it actually detect?", a: "Deviations in hours, activity, and output, plus sustained overtime and after-hours patterns that indicate burnout risk." },
      { q: "Does it make decisions for me?", a: "It surfaces an explainable, ranked list of who to check in with — the human stays in control." },
    ],
    cta: { title: "Catch burnout before it cracks a team.", body: "Let the models surface risk early, in language anyone can act on." },
  },

  integrations: {
    slug: "integrations",
    eyebrow: "Integrations & API",
    icon: Plug,
    title: "Connect your stack — connectors, REST API, and webhooks.",
    lede: "Native connectors for Slack, Teams, Jira, GitHub, and Google Workspace, plus a documented REST API, webhooks, OAuth 2.0, and SCIM 2.0 directory sync.",
    problem: {
      heading: "A workforce platform that won't connect is just another silo.",
      body: "Point tools that don't integrate create swivel-chair work and stale data. WorkPulse is API-first, so it fits the stack you already run instead of replacing it.",
    },
    capabilities: [
      { icon: Plug, title: "Native connectors", body: "One-click connectors for Slack, Microsoft Teams, Jira, GitHub, Google Workspace, and more." },
      { icon: Webhook, title: "Webhooks", body: "Subscribe to events and push real-time changes into your downstream systems." },
      { icon: Database, title: "REST API", body: "A documented, versioned REST API for every core object — time, projects, people, reports." },
      { icon: KeyRound, title: "OAuth 2.0", body: "Standard OAuth 2.0 authorization for secure, scoped third-party access." },
      { icon: RefreshCw, title: "SCIM 2.0 directory sync", body: "Automated user and group provisioning from your identity provider." },
      { icon: Bell, title: "Notification routing", body: "Route alerts and approvals to Slack / Teams channels and email." },
    ],
    how: {
      heading: "API-first, by design.",
      steps: [
        { title: "Connect", body: "Authorize a connector via OAuth, or generate API keys and webhook endpoints." },
        { title: "Sync", body: "Users provision via SCIM; objects sync bidirectionally over the REST API." },
        { title: "Automate", body: "Webhooks trigger your workflows the moment something changes in WorkPulse." },
      ],
    },
    specs: [
      { label: "API", value: "REST, versioned" },
      { label: "Auth", value: "OAuth 2.0 · API keys" },
      { label: "Events", value: "Webhooks" },
      { label: "Provisioning", value: "SCIM 2.0" },
      { label: "Connectors", value: "Slack · Teams · Jira · GitHub" },
      { label: "Rate limits", value: "Per-key, documented" },
    ],
    related: ["security", "workforce", "reports"],
    faqs: [
      { q: "Is there a public API?", a: "Yes — a documented, versioned REST API covers every core object, with webhooks for real-time events." },
      { q: "How do users provision?", a: "SCIM 2.0 syncs users and groups from your identity provider automatically." },
      { q: "Which tools connect natively?", a: "Slack, Microsoft Teams, Jira, GitHub, Google Workspace, and more, with new connectors added regularly." },
    ],
    cta: { title: "Fit the stack you already run.", body: "Connect WorkPulse with native connectors, a REST API, and webhooks." },
  },

  security: {
    slug: "security",
    eyebrow: "Security & Compliance",
    icon: ShieldCheck,
    title: "Enterprise security and compliance, built in — not bolted on.",
    lede: "SSO via SAML 2.0 and OIDC, SCIM provisioning, RBAC, immutable audit logs, configurable data residency, and AES-256 / TLS 1.3 encryption — backed by SOC 2 Type II.",
    problem: {
      heading: "Security review shouldn't be where deals go to die.",
      body: "Enterprise buyers need SSO, audit trails, residency, and least-privilege access before they sign. WorkPulse ships these as first-class capabilities your security team can verify.",
    },
    capabilities: [
      { icon: KeyRound, title: "SSO — SAML 2.0 & OIDC", body: "Single sign-on via SAML 2.0 and OpenID Connect with your existing identity provider." },
      { icon: RefreshCw, title: "SCIM 2.0 provisioning", body: "Automated user and group lifecycle, synced from your directory." },
      { icon: Lock, title: "MFA & session policies", body: "Enforce multi-factor auth, session timeouts, and device-level controls." },
      { icon: ScrollText, title: "Immutable audit logs", body: "Every action, permission change, and login captured in a tamper-evident trail." },
      { icon: Globe, title: "Data residency & encryption", body: "Choose your residency region; data is encrypted at rest (AES-256) and in transit (TLS 1.3)." },
      { icon: Headset, title: "Approval-gated remote support", body: "Consent-based remote sessions and managed desktop agents — fully audited." },
    ],
    how: {
      heading: "Defense in depth, end to end.",
      steps: [
        { title: "Authenticate", body: "Users sign in through SSO with enforced MFA; access maps to least-privilege roles." },
        { title: "Authorize & log", body: "RBAC governs every action; the immutable audit log records it all." },
        { title: "Govern", body: "Set residency, retention, and DPA terms; agents and remote sessions stay approval-gated." },
      ],
    },
    specs: [
      { label: "SSO", value: "SAML 2.0 · OIDC" },
      { label: "Provisioning", value: "SCIM 2.0" },
      { label: "Encryption", value: "AES-256 · TLS 1.3" },
      { label: "Audit", value: "Immutable · exportable" },
      { label: "Residency", value: "Configurable regions" },
      { label: "Compliance", value: "SOC 2 Type II · GDPR · DPA" },
    ],
    related: ["workforce", "integrations", "activity-monitoring"],
    faqs: [
      { q: "Which SSO standards are supported?", a: "SAML 2.0 and OIDC, with SCIM 2.0 for automated provisioning from your IdP." },
      { q: "Where is data stored?", a: "You choose a data-residency region; data is encrypted at rest (AES-256) and in transit (TLS 1.3)." },
      { q: "Can we get an audit trail and DPA?", a: "Yes — an immutable, exportable audit log plus a signed DPA are available on the Max plan." },
    ],
    cta: { title: "Pass security review with room to spare.", body: "Give IT the SSO, audit, residency, and controls they require — out of the box." },
  },
};
