import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Timer,
  FolderKanban,
  Users,
  Activity,
  Camera,
  MapPin,
  CheckCheck,
  WandSparkles,
  LineChart,
  Bell,
  BellRing,
  ShieldCheck,
  MonitorSmartphone,
  KeyRound,
  ScrollText,
  Settings,
  HelpCircle,
  Building2,
  CalendarCheck,
  Wallet,
  DoorOpen,
  SlidersHorizontal,
  Globe,
  ToggleRight,
  Plug,
  TriangleAlert,
  User,
  CreditCard,
  Palette,
} from "lucide-react";
import type { PermissionId } from "@/types/rbac";

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  /** Permission required to see this item. null = always visible. */
  permission: PermissionId | null;
  /** If set, item is visible when the role holds ANY of these (overrides `permission` for visibility). */
  anyPermissions?: PermissionId[];
  /** Short description, shown in the Settings/admin hub or Insights tabs. */
  description?: string;
  /** Extra search synonyms (e.g. "mfa 2fa multifactor") so global search finds
   *  a section by what it contains, not just its label. */
  keywords?: string;
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

/**
 * Lean sidebar — only day-to-day destinations (SPEC.md §3). Admin/config
 * sections live in the Settings hub (see ADMIN_SECTIONS). The sidebar is
 * generated by filtering this tree through the active role's permissions
 * (getAccessibleNav in lib/rbac.ts).
 */
export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Work",
    items: [
      {
        label: "Dashboard",
        href: "/dashboard",
        icon: LayoutDashboard,
        permission: "dashboard:view",
        keywords: "home overview widgets summary productivity score my day",
      },
      {
        label: "Time Tracking",
        href: "/time-tracking",
        icon: Timer,
        permission: "time-tracking:view",
        keywords: "timer timesheet hours sessions billable work log clock in out",
      },
      {
        label: "Projects",
        href: "/projects",
        icon: FolderKanban,
        permission: "projects:view",
        keywords: "tasks board kanban backlog milestones deadlines assignments",
      },
    ],
  },
  {
    label: "Manage",
    items: [
      {
        label: "Employees",
        href: "/employees",
        icon: Users,
        permission: "employees:view",
        keywords: "people directory staff team members invite hire onboarding profile",
      },
      {
        label: "Attendance",
        href: "/attendance",
        icon: CalendarCheck,
        permission: "attendance:view",
        keywords: "present absent late check in checkout shifts calendar days off",
      },
      {
        label: "Leave",
        href: "/leave-requests",
        icon: DoorOpen,
        // `leave:view` is contributor-only, so the "*" wildcard does NOT grant it — which is why the
        // Owner has never seen this page at all. `anyPermissions` admits the oversight side
        // (`leave:manage`, a normal permission the wildcard does grant), and `permission: null`
        // keeps the route itself reachable — the same pairing Analytics uses, because
        // `permissionForPath` reads only `permission` and would otherwise block what the nav offers.
        // Nothing leaks: the page renders the self-scoped employee view by default, and every
        // oversight section inside it is gated on `leave:manage` again.
        permission: null,
        anyPermissions: ["leave:view", "leave:manage"],
        keywords: "vacation holiday pto sick time off request balance allowance wfh",
      },
      {
        label: "Approvals",
        href: "/approvals",
        icon: CheckCheck,
        permission: "approvals:view",
        keywords: "pending requests approve reject review queue sign off",
      },
      {
        label: "Payroll",
        href: "/payroll",
        icon: Wallet,
        permission: "payroll:view",
        keywords: "salary payslip compensation deductions pay run wages money",
      },
      {
        label: "Analytics",
        href: "/insights",
        icon: LineChart,
        permission: null,
        anyPermissions: [
          "activity:view",
          "screenshots:view",
          "reports:view",
          "ai:view",
        ],
        keywords: "insights reports activity monitoring charts statistics trends",
      },
    ],
  },
  {
    label: "Communication",
    items: [
      {
        label: "Notifications",
        href: "/notifications",
        icon: Bell,
        permission: "notifications:view",
        keywords: "alerts unread mentions activity feed reminders",
      },
    ],
  },
  {
    label: "Admin",
    items: [
      // Always reachable: also hosts Appearance + the admin hub (incl. Billing).
      // Admin cards inside are individually permission-gated.
      {
        label: "Settings",
        href: "/settings",
        icon: Settings,
        permission: null,
        keywords: "preferences configuration options account organization admin hub",
      },
      {
        label: "Help Center",
        href: "/help",
        icon: HelpCircle,
        permission: "help:view",
        keywords: "support docs documentation faq guide ticket contact how to",
      },
    ],
  },
];

/**
 * Insights tabs — the Activity / Screenshots / AI Insights / Reports
 * sections, merged into one tabbed `/insights` page. Rendered as a tab bar
 * (filtered by permission) and scanned by permissionForPath so each tab keeps
 * its own route guard.
 */
export const INSIGHTS_TABS: NavItem[] = [
  {
    label: "Activity",
    href: "/insights/activity",
    icon: Activity,
    permission: "activity:view",
    description: "Active vs inactive, heatmaps, app & URL usage.",
    keywords: "productivity idle heatmap apps websites usage monitoring keystrokes",
  },
  {
    label: "Screenshots",
    href: "/insights/screenshots",
    icon: Camera,
    permission: "screenshots:view",
    description: "Screenshot gallery, timeline, and risk analysis.",
    keywords: "captures images gallery monitor review flagged blur",
  },
  {
    label: "Locations",
    href: "/insights/locations",
    icon: MapPin,
    permission: "locations:view",
    description: "Live employee locations, login/logout trail, and map.",
    keywords: "map gps geolocation whereabouts remote field trail tracking",
  },
  {
    label: "AI reports",
    href: "/insights/ai-reports",
    icon: WandSparkles,
    permission: "reports:view",
    description:
      "AI summary, workforce health, alerts, and exportable reports in one place.",
    keywords: "summary anomalies alerts export pdf csv workforce health assistant",
  },
];

/**
 * Personal account settings sub-sections — the Settings hub's "Account" rail
 * group. Shared so global search can surface them and the settings layout can
 * build its rail from a single source. Always accessible (permission: null).
 */
export const ACCOUNT_SECTIONS: NavItem[] = [
  {
    label: "Profile",
    href: "/settings/profile",
    icon: User,
    permission: null,
    description: "Your account and personal details.",
    keywords: "name email avatar photo personal account details job title",
  },
  {
    label: "Notification preferences",
    href: "/settings/notifications",
    icon: BellRing,
    permission: null,
    description: "Email and in-app notification preferences.",
    keywords: "alerts email digest preferences push reminders notifications",
  },
  {
    label: "Appearance",
    href: "/settings/appearance",
    icon: Palette,
    permission: null,
    description: "Theme, palette, and display density.",
    keywords: "theme palette colour color dark light mode density font",
  },
];

/**
 * Deep-link search targets — individual cards/sections WITHIN a settings page.
 * The href carries an `#anchor` that matches an element id on the page, so
 * global search lands on the exact section, not just the top of the page.
 */
export const SETTINGS_SUBSECTIONS: NavItem[] = [
  {
    // Read-only company reference for EVERY member — the audience the admin Organization editor
    // (settings:view) never had. `permission: null` so employees, who lack settings:view, see it.
    label: "Company",
    href: "/settings/company",
    icon: Building2,
    permission: null,
    description: "Organization details, working hours, holidays, and policies.",
    keywords: "company organization policies holidays working hours schedule handbook rules reference",
  },
  {
    label: "Login & security",
    href: "/settings/login-security",
    icon: KeyRound,
    permission: null,
    description: "Change your password and manage your authenticator app.",
    keywords:
      "password change reset credentials mfa 2fa authenticator totp enrol enroll disable qr code login security",
  },
  {
    label: "Export organization data",
    href: "/settings/ownership",
    icon: TriangleAlert,
    permission: "settings:manage",
    description: "Request a full export of your organization's data.",
    keywords: "export download all data backup zip archive gdpr copy organization",
  },
  {
    label: "Multi-factor authentication",
    href: "/settings/security#mfa",
    icon: ShieldCheck,
    permission: "security:view",
    description: "Multi-factor / authenticator setup and policy.",
    keywords:
      "mfa 2fa multifactor multi-factor two-factor authenticator otp passkey two step verification",
  },
  {
    label: "Session & access policies",
    href: "/settings/security#sessions",
    icon: ShieldCheck,
    permission: "security:view",
    description: "Session timeout, device limits, and trusted devices.",
    keywords: "session timeout concurrent device trusted remember access policy",
  },
];

/**
 * Admin & configuration sections — relocated out of the sidebar into the
 * Settings hub. Still routed and permission-gated: permissionForPath() scans
 * these too, and the hub filters cards by the active role's permissions.
 */
export const ADMIN_SECTIONS: NavGroup[] = [
  {
    label: "Organization",
    items: [
      {
        label: "Organization",
        href: "/settings/organization",
        icon: Building2,
        permission: "settings:view",
        description: "Organization info, departments, teams, working hours, and branding.",
        keywords: "organization company department team workspace working hours branding logo timezone",
      },
      {
        label: "Features",
        href: "/settings/features",
        icon: ToggleRight,
        permission: "settings:view",
        description: "Turn modules on or off for the whole organization.",
        keywords: "modules toggle enable disable features flags",
      },
      {
        label: "Billing",
        href: "/settings/billing",
        icon: CreditCard,
        permission: "billing:view",
        description: "Plan, seats, payment method, and invoices.",
        keywords: "invoice payment plan subscription seats card receipt billing cancel",
      },
      {
        label: "Ownership & deletion",
        href: "/settings/ownership",
        icon: TriangleAlert,
        permission: "settings:manage",
        description: "Transfer ownership, export data, or close the organization.",
        keywords: "transfer ownership export data close delete danger zone",
      },
    ],
  },
  {
    label: "Monitoring & tracking",
    items: [
      {
        label: "Monitoring",
        href: "/settings/monitoring",
        icon: SlidersHorizontal,
        permission: "settings:view",
        description: "Idle, screenshot, and productivity thresholds.",
        keywords: "idle screenshot productivity threshold tracking monitoring",
      },
      {
        label: "Tracking rules",
        href: "/settings/tracking-rules",
        icon: Globe,
        permission: "settings:view",
        description: "Allow lists, block lists, and productivity scoring.",
        keywords: "allow list block list apps url website productivity scoring rules",
      },
    ],
  },
  {
    label: "Access & security",
    items: [
      {
        label: "Roles & permissions",
        href: "/settings/roles",
        icon: KeyRound,
        permission: "roles:view",
        description: "Create roles and control what each can access.",
        keywords: "rbac access permissions role custom grant",
      },
      {
        label: "Security",
        href: "/settings/security",
        icon: ShieldCheck,
        permission: "security:view",
        description: "MFA, SSO, session policies, and security events.",
        keywords: "security center protect compliance events policy",
      },
      {
        label: "Audit logs",
        href: "/settings/audit-logs",
        icon: ScrollText,
        permission: "audit-logs:view",
        description: "User actions, permission changes, and login events.",
        keywords: "activity log history events sign-in audit trail",
      },
    ],
  },
  {
    label: "Infrastructure",
    items: [
      {
        label: "Integrations",
        href: "/settings/integrations",
        icon: Plug,
        permission: "integrations:view",
        description: "Slack, Teams, Jira, GitHub, and more.",
        keywords: "connect apps slack teams jira github webhook api marketplace",
      },
      {
        label: "Device agents",
        href: "/settings/agents",
        icon: MonitorSmartphone,
        permission: "agents:view",
        description: "Device agent status, configuration, policies, and health.",
        keywords:
          "download install installer setup desktop app tracker agent fleet devices windows mac laptop computer monitor health heartbeat offline",
      },
    ],
  },
];

/**
 * Every navigable destination in one flat list — sidebar, Insights tabs, account, settings and the
 * admin hub.
 *
 * Exists so a **path** can be resolved back to what that page is, which is what the assistant needs
 * to answer "what is this page for". It is deliberately built from the same entries that render the
 * navigation: a renamed route and its wording change in one place, so the answer cannot drift from
 * the product the way a second, hand-kept description table would.
 */
export const ALL_NAV_ITEMS: NavItem[] = [
  ...NAV_GROUPS.flatMap((g) => g.items),
  ...INSIGHTS_TABS,
  ...ACCOUNT_SECTIONS,
  ...SETTINGS_SUBSECTIONS,
  ...ADMIN_SECTIONS.flatMap((g) => g.items),
];

/**
 * The navigation entry a pathname belongs to, or `null`.
 *
 * **Longest matching `href` wins**, so `/settings/roles` resolves to Roles & Permissions rather
 * than to `/settings`, and a detail route like `/employees/abc` still resolves to Employees — a
 * detail page is about the same thing as its list. Any `#fragment` on an entry is ignored: it is a
 * scroll target, not a different page.
 */
export function navItemForPath(pathname: string): NavItem | null {
  const path = pathname.split("?")[0].replace(/\/+$/, "") || "/";
  let best: NavItem | null = null;
  for (const item of ALL_NAV_ITEMS) {
    const href = item.href.split("#")[0].replace(/\/+$/, "");
    if (!href) continue;
    if (path === href || path.startsWith(`${href}/`)) {
      if (!best || href.length > best.href.split("#")[0].replace(/\/+$/, "").length) {
        best = item;
      }
    }
  }
  return best;
}
