import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Timer,
  FolderKanban,
  Users,
  Activity,
  Camera,
  FileBarChart,
  CheckCheck,
  Sparkles,
  LineChart,
  Mail,
  Bell,
  CreditCard,
  ShieldCheck,
  MonitorSmartphone,
  Headset,
  KeyRound,
  ScrollText,
  Settings,
  HelpCircle,
  Building2,
  CalendarCheck,
  Wallet,
  SlidersHorizontal,
  Globe,
  ToggleRight,
  Plug,
  TriangleAlert,
} from "lucide-react";
import type { PermissionId } from "@/types/rbac";

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  /** Permission required to see this item. null = always visible. */
  permission: PermissionId | null;
  /** If set, item is visible when the role holds ANY of these (overrides `permission` for visibility). */
  anyPermissions?: PermissionId[];
  /** Short description, shown in the Settings/admin hub or Insights tabs. */
  description?: string;
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

/**
 * Lean sidebar — only day-to-day destinations (SPEC.md §3). Admin/config
 * sections live in the Settings hub (see ADMIN_SECTIONS). The sidebar is
 * generated by filtering this tree through the active role's permissions
 * (getAccessibleNav in lib/rbac.ts).
 */
export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Workspace",
    items: [
      { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, permission: "dashboard:view" },
      { label: "Time Tracking", href: "/time-tracking", icon: Timer, permission: "time-tracking:view" },
      { label: "Projects", href: "/projects", icon: FolderKanban, permission: "projects:view" },
    ],
  },
  {
    label: "Insights",
    items: [
      {
        label: "Insights",
        href: "/insights",
        icon: LineChart,
        permission: null,
        anyPermissions: [
          "activity:view",
          "screenshots:view",
          "reports:view",
          "ai:view",
        ],
      },
    ],
  },
  {
    label: "People",
    items: [
      { label: "Employees", href: "/employees", icon: Users, permission: "employees:view" },
      { label: "Attendance", href: "/attendance", icon: CalendarCheck, permission: "attendance:view" },
      { label: "Payroll", href: "/payroll", icon: Wallet, permission: "payroll:view" },
      { label: "Approvals", href: "/approvals", icon: CheckCheck, permission: "approvals:view" },
    ],
  },
  {
    label: "Communication",
    items: [
      { label: "Inbox", href: "/inbox", icon: Mail, permission: "communication:view" },
      { label: "Notifications", href: "/notifications", icon: Bell, permission: "notifications:view" },
    ],
  },
  {
    label: "Account",
    items: [
      { label: "Billing", href: "/billing", icon: CreditCard, permission: "billing:view" },
      // Always reachable: also hosts Appearance + the admin hub. Admin cards
      // inside are individually permission-gated.
      { label: "Settings", href: "/settings", icon: Settings, permission: null },
      { label: "Help Center", href: "/help", icon: HelpCircle, permission: "help:view" },
    ],
  },
];

/**
 * Insights tabs — the Activity / Screenshots / AI Insights / Reports
 * sections, merged into one tabbed `/insights` page. Rendered as a tab bar
 * (filtered by permission) and scanned by permissionForPath so each tab keeps
 * its own route guard.
 */
export const INSIGHTS_TABS: NavItem[] = [
  {
    label: "Activity",
    href: "/insights/activity",
    icon: Activity,
    permission: "activity:view",
    description: "Active vs inactive, heatmaps, app & URL usage.",
  },
  {
    label: "Screenshots",
    href: "/insights/screenshots",
    icon: Camera,
    permission: "screenshots:view",
    description: "Screenshot gallery, timeline, and risk analysis.",
  },
  {
    label: "AI Insights",
    href: "/insights/anomalies",
    icon: Sparkles,
    permission: "ai:view",
    description: "AI summaries, recommendations, and people who need attention.",
  },
  {
    label: "Reports",
    href: "/insights/reports",
    icon: FileBarChart,
    permission: "reports:view",
    description: "Productivity, time, project, and AI reports with export.",
  },
];

/**
 * Admin & configuration sections — relocated out of the sidebar into the
 * Settings hub. Still routed and permission-gated: permissionForPath() scans
 * these too, and the hub filters cards by the active role's permissions.
 */
export const ADMIN_SECTIONS: NavGroup[] = [
  {
    label: "Organization",
    items: [
      {
        label: "Organization",
        href: "/settings/organization",
        icon: Building2,
        permission: "settings:view",
        description: "Company info, departments, teams, working hours, and branding.",
      },
      {
        label: "Feature management",
        href: "/settings/features",
        icon: ToggleRight,
        permission: "settings:view",
        description: "Turn modules on or off for the whole organization.",
      },
      {
        label: "Ownership & deletion",
        href: "/settings/ownership",
        icon: TriangleAlert,
        permission: "settings:manage",
        description: "Transfer ownership, export data, or close the organization.",
      },
    ],
  },
  {
    label: "Monitoring & tracking",
    items: [
      {
        label: "Monitoring",
        href: "/settings/monitoring",
        icon: SlidersHorizontal,
        permission: "settings:view",
        description: "Idle, screenshot, and productivity thresholds.",
      },
      {
        label: "Application & URL rules",
        href: "/settings/tracking-rules",
        icon: Globe,
        permission: "settings:view",
        description: "Allow lists, block lists, and productivity scoring.",
      },
    ],
  },
  {
    label: "Access & security",
    items: [
      {
        label: "Roles & Permissions",
        href: "/settings/roles",
        icon: KeyRound,
        permission: "roles:view",
        description: "Create roles and control what each can access.",
      },
      {
        label: "Security",
        href: "/settings/security",
        icon: ShieldCheck,
        permission: "security:view",
        description: "MFA, SSO, session policies, and security events.",
      },
      {
        label: "Audit Logs",
        href: "/settings/audit-logs",
        icon: ScrollText,
        permission: "audit-logs:view",
        description: "User actions, permission changes, and login events.",
      },
    ],
  },
  {
    label: "Infrastructure",
    items: [
      {
        label: "Integrations",
        href: "/settings/integrations",
        icon: Plug,
        permission: "integrations:view",
        description: "Slack, Teams, Jira, GitHub, and more.",
      },
      {
        label: "Remote Support",
        href: "/settings/remote-support",
        icon: Headset,
        permission: "remote-support:view",
        description: "Approval-gated remote support sessions and diagnostics.",
      },
      {
        label: "Desktop Agents",
        href: "/settings/agents",
        icon: MonitorSmartphone,
        permission: "agents:view",
        description: "Agent status, configuration, policies, and health.",
      },
    ],
  },
];
