import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Timer,
  FolderKanban,
  Users,
  Activity,
  Camera,
  MapPin,
  CheckCheck,
  WandSparkles,
  LineChart,
  Mail,
  Bell,
  ShieldCheck,
  MonitorSmartphone,
  KeyRound,
  ScrollText,
  Settings,
  HelpCircle,
  Building2,
  CalendarCheck,
  Wallet,
  DoorOpen,
  SlidersHorizontal,
  Globe,
  ToggleRight,
  Plug,
  TriangleAlert,
  User,
  CreditCard,
  Palette,
} from "lucide-react";
import type { PermissionId } from "@/types/rbac";

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  /** Permission required to see this item. null = always visible. */
  permission: PermissionId | null;
  /** If set, item is visible when the role holds ANY of these (overrides `permission` for visibility). */
  anyPermissions?: PermissionId[];
  /** Short description, shown in the Settings/admin hub or Insights tabs. */
  description?: string;
  /** Extra search synonyms (e.g. "mfa 2fa multifactor") so global search finds
   *  a section by what it contains, not just its label. */
  keywords?: string;
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

/**
 * Lean sidebar — only day-to-day destinations (SPEC.md §3). Admin/config
 * sections live in the Settings hub (see ADMIN_SECTIONS). The sidebar is
 * generated by filtering this tree through the active role's permissions
 * (getAccessibleNav in lib/rbac.ts).
 */
export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Work",
    items: [
      { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, permission: "dashboard:view" },
      { label: "Time Tracking", href: "/time-tracking", icon: Timer, permission: "time-tracking:view" },
      { label: "Projects", href: "/projects", icon: FolderKanban, permission: "projects:view" },
    ],
  },
  {
    label: "Manage",
    items: [
      { label: "Employees", href: "/employees", icon: Users, permission: "employees:view" },
      { label: "Attendance", href: "/attendance", icon: CalendarCheck, permission: "attendance:view" },
      { label: "Leave", href: "/leave-requests", icon: DoorOpen, permission: "leave:view" },
      { label: "Approvals", href: "/approvals", icon: CheckCheck, permission: "approvals:view" },
      { label: "Payroll", href: "/payroll", icon: Wallet, permission: "payroll:view" },
      {
        label: "Analytics",
        href: "/insights",
        icon: LineChart,
        permission: null,
        anyPermissions: [
          "activity:view",
          "screenshots:view",
          "reports:view",
          "ai:view",
        ],
      },
    ],
  },
  {
    label: "Communication",
    items: [
      { label: "Inbox", href: "/inbox", icon: Mail, permission: "communication:view" },
      { label: "Notifications", href: "/notifications", icon: Bell, permission: "notifications:view" },
    ],
  },
  {
    label: "Admin",
    items: [
      // Always reachable: also hosts Appearance + the admin hub (incl. Billing).
      // Admin cards inside are individually permission-gated.
      { label: "Settings", href: "/settings", icon: Settings, permission: null },
      { label: "Help Center", href: "/help", icon: HelpCircle, permission: "help:view" },
    ],
  },
];

/**
 * Insights tabs — the Activity / Screenshots / AI Insights / Reports
 * sections, merged into one tabbed `/insights` page. Rendered as a tab bar
 * (filtered by permission) and scanned by permissionForPath so each tab keeps
 * its own route guard.
 */
export const INSIGHTS_TABS: NavItem[] = [
  {
    label: "Activity",
    href: "/insights/activity",
    icon: Activity,
    permission: "activity:view",
    description: "Active vs inactive, heatmaps, app & URL usage.",
  },
  {
    label: "Screenshots",
    href: "/insights/screenshots",
    icon: Camera,
    permission: "screenshots:view",
    description: "Screenshot gallery, timeline, and risk analysis.",
  },
  {
    label: "Locations",
    href: "/insights/locations",
    icon: MapPin,
    permission: "locations:view",
    description: "Live employee locations, login/logout trail, and map.",
  },
  {
    label: "AI Insights & Reports",
    href: "/insights/ai-reports",
    icon: WandSparkles,
    permission: "reports:view",
    description:
      "AI briefing, workforce health, attention signals, and exportable reports in one place.",
  },
];

/**
 * Personal account settings sub-sections — the Settings hub's "Account" rail
 * group. Shared so global search can surface them and the settings layout can
 * build its rail from a single source. Always accessible (permission: null).
 */
export const ACCOUNT_SECTIONS: NavItem[] = [
  {
    label: "Profile",
    href: "/settings/profile",
    icon: User,
    permission: null,
    description: "Your account and personal details.",
    keywords: "name email avatar photo personal account details job title",
  },
  {
    label: "Notifications",
    href: "/settings/notifications",
    icon: Bell,
    permission: null,
    description: "Email and in-app notification preferences.",
    keywords: "alerts email digest preferences push reminders",
  },
  {
    label: "Appearance",
    href: "/settings/appearance",
    icon: Palette,
    permission: null,
    description: "Theme, palette, and display density.",
    keywords: "theme palette colour color dark light mode density font",
  },
];

/**
 * Deep-link search targets — individual cards/sections WITHIN a settings page.
 * The href carries an `#anchor` that matches an element id on the page, so
 * global search lands on the exact section, not just the top of the page.
 */
export const SETTINGS_SUBSECTIONS: NavItem[] = [
  {
    label: "Multi-factor authentication",
    href: "/settings/security#mfa",
    icon: ShieldCheck,
    permission: "security:view",
    description: "Two-factor / authenticator setup and policy.",
    keywords:
      "mfa 2fa multifactor multi-factor two-factor authenticator otp passkey two step verification",
  },
  {
    label: "Single sign-on (SSO)",
    href: "/settings/security#sso",
    icon: ShieldCheck,
    permission: "security:view",
    description: "SAML / SSO identity provider connection.",
    keywords: "sso single sign-on saml okta azure identity provider idp",
  },
  {
    label: "Session & access policies",
    href: "/settings/security#sessions",
    icon: ShieldCheck,
    permission: "security:view",
    description: "Session timeout, device limits, and trusted devices.",
    keywords: "session timeout concurrent device trusted remember access policy",
  },
];

/**
 * Admin & configuration sections — relocated out of the sidebar into the
 * Settings hub. Still routed and permission-gated: permissionForPath() scans
 * these too, and the hub filters cards by the active role's permissions.
 */
export const ADMIN_SECTIONS: NavGroup[] = [
  {
    label: "Organization",
    items: [
      {
        label: "Organization",
        href: "/settings/organization",
        icon: Building2,
        permission: "settings:view",
        description: "Company info, departments, teams, working hours, and branding.",
        keywords: "company department team workspace working hours branding logo timezone",
      },
      {
        label: "Feature management",
        href: "/settings/features",
        icon: ToggleRight,
        permission: "settings:view",
        description: "Turn modules on or off for the whole organization.",
        keywords: "modules toggle enable disable features flags",
      },
      {
        label: "Billing",
        href: "/settings/billing",
        icon: CreditCard,
        permission: "billing:view",
        description: "Plan, seats, payment method, and invoices.",
        keywords: "invoice payment plan subscription seats card receipt billing cancel",
      },
      {
        label: "Ownership & deletion",
        href: "/settings/ownership",
        icon: TriangleAlert,
        permission: "settings:manage",
        description: "Transfer ownership, export data, or close the organization.",
        keywords: "transfer ownership export data close delete danger zone",
      },
    ],
  },
  {
    label: "Monitoring & tracking",
    items: [
      {
        label: "Monitoring",
        href: "/settings/monitoring",
        icon: SlidersHorizontal,
        permission: "settings:view",
        description: "Idle, screenshot, and productivity thresholds.",
        keywords: "idle screenshot productivity threshold tracking monitoring",
      },
      {
        label: "Application & URL rules",
        href: "/settings/tracking-rules",
        icon: Globe,
        permission: "settings:view",
        description: "Allow lists, block lists, and productivity scoring.",
        keywords: "allow list block list apps url website productivity scoring rules",
      },
    ],
  },
  {
    label: "Access & security",
    items: [
      {
        label: "Roles & Permissions",
        href: "/settings/roles",
        icon: KeyRound,
        permission: "roles:view",
        description: "Create roles and control what each can access.",
        keywords: "rbac access permissions role custom grant",
      },
      {
        label: "Security",
        href: "/settings/security",
        icon: ShieldCheck,
        permission: "security:view",
        description: "MFA, SSO, session policies, and security events.",
        keywords: "security center protect compliance events policy",
      },
      {
        label: "Audit Logs",
        href: "/settings/audit-logs",
        icon: ScrollText,
        permission: "audit-logs:view",
        description: "User actions, permission changes, and login events.",
        keywords: "activity log history events sign-in audit trail",
      },
    ],
  },
  {
    label: "Infrastructure",
    items: [
      {
        label: "Integrations",
        href: "/settings/integrations",
        icon: Plug,
        permission: "integrations:view",
        description: "Slack, Teams, Jira, GitHub, and more.",
      },
      {
        label: "Desktop Agents",
        href: "/settings/agents",
        icon: MonitorSmartphone,
        permission: "agents:view",
        description: "Agent status, configuration, policies, and health.",
      },
    ],
  },
];
