/**
 * Guided product tours — the data behind the Help Center's "Start tour" buttons.
 *
 * A tour is a list of steps, and a step is **a route plus a target on it**. The driver
 * (`components/layout/product-tour.tsx`) navigates to `route`, waits for `target` to exist, then
 * lets Joyride highlight it. That is the whole contract, and it is what makes these tours point at
 * the real product rather than describe it.
 *
 * ## Targets are `data-tour` attributes, never CSS structure
 *
 * Every selector here is `[data-tour="…"]`. Tempting alternatives — `.wp-stat-card`, `nav a:nth-child(2)` —
 * are class names and layout, which change for reasons that have nothing to do with the tour and
 * break it silently. A `data-tour` attribute is a *declared* contract: someone deleting it can see
 * what it was for.
 *
 * Sidebar items are addressable as `nav:<href>` for free (`sidebar-nav.tsx` stamps them from the
 * nav tree), so a step that just wants to show someone where a section lives needs no new markup.
 *
 * ## Every step must be allowed to be missing
 *
 * The sidebar is generated by filtering the nav tree through the caller's permissions, so an
 * employee genuinely has no Employees link and no Settings link. A tour that assumed otherwise
 * would dead-end mid-way for the people most likely to be taking it. `permission` lets a step
 * declare what it needs; the driver drops steps the caller can't see **before** the tour starts, so
 * the step count is honest ("2 of 3", not "2 of 6" with four skips). A step whose target is missing
 * for any other reason is skipped at runtime rather than stalling.
 */
import type { PermissionId } from "@/types/rbac";

export interface TourStep {
  /** Route this step lives on. The driver navigates here first if we aren't already. */
  route: string;
  /** `data-tour` value of the element to highlight. Omit to centre the step on the page. */
  target?: string;
  title: string;
  content: string;
  /** Required to see the target. Steps whose permission the caller lacks are dropped up front. */
  permission?: PermissionId;
}

export interface Tour {
  id: string;
  /**
   * What a person needs to be offered this tour at all — the gate on the Help Center's card.
   *
   * Lives here, beside the steps, rather than in the page: the card's gate and the steps' gates are
   * the same idea, and when they were separate they could drift into a card that opens a tour with
   * no steps — a button that does nothing. `tours.test.ts` asserts they agree.
   */
  permission?: PermissionId;
  steps: TourStep[];
}

/**
 * Keyed by the walkthrough ids the Help Center already renders, so the buttons need no mapping
 * table — a tour is present or the button explains that it isn't.
 */
export const TOURS: Record<string, Tour> = {
  "getting-started": {
    id: "getting-started",
    steps: [
      {
        route: "/dashboard",
        title: "This is your dashboard",
        content:
          "Everything at a glance: what you're tracking right now, your open work, and how the week is going. We'll walk through it.",
      },
      {
        route: "/dashboard",
        target: "dash:greeting",
        title: "Your day, summarised",
        content:
          "The header tells you whose view this is and what day it covers. An Owner sees the organization; everyone else sees their own work.",
      },
      {
        route: "/dashboard",
        target: "dash:kpis",
        title: "The numbers that matter",
        content:
          "Your headline figures for the period. They come from what the desktop agent actually reported — a dash means no data yet, never a guess.",
      },
      {
        route: "/dashboard",
        target: "nav:/time-tracking",
        title: "Where your hours live",
        content:
          "Every session the agent recorded, day by day. The web view is read-only — the desktop app does the tracking.",
      },
      {
        route: "/dashboard",
        target: "nav:/projects",
        title: "Where the work lives",
        content:
          "Projects and tasks live here. That's the tour — every section in the sidebar has its own walkthrough in the Help Center.",
      },
    ],
  },

  "time-tracking": {
    id: "time-tracking",
    steps: [
      {
        route: "/dashboard",
        target: "nav:/time-tracking",
        title: "Time Tracking",
        content: "Your timesheet lives here — every session, every day.",
      },
      {
        route: "/time-tracking",
        title: "The desktop agent does the tracking",
        content:
          "There is no start/stop button on the web, by design. The WorkPulse desktop agent records your sessions and the server folds them into this timesheet, so what you see here always matches what was actually captured.",
      },
      {
        route: "/time-tracking",
        title: "Today's totals",
        content:
          "Tracked and billable time for the day. A session that's still open shows as running and hasn't contributed settled time yet.",
      },
      {
        route: "/attendance",
        title: "Attendance is the other half",
        content:
          "Sessions become attendance: present days, hours worked and lateness. Both are derived from the same agent batches, so they can't disagree.",
      },
    ],
  },

  insights: {
    id: "insights",
    permission: "reports:view",
    steps: [
      {
        route: "/dashboard",
        target: "nav:/insights",
        title: "Analytics",
        content: "Productivity scores, trends and anomalies live here.",
        permission: "reports:view",
      },
      {
        route: "/insights",
        title: "How the score is built",
        content:
          "A deterministic 0–100 from four parts — utilization, quality, focus and reliability. Rust computes it from the day's activity; the AI never decides your score, it only narrates it.",
        permission: "reports:view",
      },
      {
        route: "/insights",
        title: "Anomalies flag the exceptions",
        content:
          "Overtime, idle stretches and policy hits are surfaced as anomalies so you're reading the days that need attention rather than every day.",
        permission: "reports:view",
      },
      {
        route: "/insights/screenshots",
        title: "Screenshot review",
        content:
          "Captures from the agent, each with an AI read of what was on screen. Distracting content is flagged with a reason — the reason is what makes a flag defensible.",
        permission: "screenshots:view",
      },
    ],
  },

  "team-management": {
    id: "team-management",
    permission: "employees:view",
    steps: [
      {
        route: "/dashboard",
        target: "nav:/employees",
        title: "Employees",
        content: "Your roster — invite people, set roles, organise departments and teams.",
        permission: "employees:view",
      },
      {
        route: "/employees",
        title: "Inviting someone",
        content:
          "An invite emails a one-time link and code. The account only exists once they accept it, so a pending invite is never a half-created user.",
        permission: "employees:view",
      },
      {
        route: "/employees",
        title: "Roles decide what people see",
        content:
          "A role is a set of permissions, and the sidebar is generated from it — someone without Payroll access doesn't see a locked Payroll page, they don't see Payroll at all.",
        permission: "employees:view",
      },
      {
        route: "/settings/roles",
        title: "Custom roles",
        content:
          "Build your own roles when the system ones don't fit. You can only grant permissions you hold yourself, so a role can never escalate beyond its author.",
        permission: "settings:view",
      },
    ],
  },

  "monitoring-setup": {
    id: "monitoring-setup",
    permission: "settings:view",
    steps: [
      {
        route: "/dashboard",
        target: "nav:/settings",
        title: "Settings",
        content: "Monitoring is configured here, org-wide.",
        permission: "settings:view",
      },
      {
        route: "/settings/monitoring",
        title: "What gets captured",
        content:
          "Screenshot cadence, blur level and retention. Blur is the lever for reducing what's legible in a capture — it's per-frame and auditable, unlike quietly lowering quality.",
        permission: "settings:view",
      },
      {
        route: "/settings/tracking-rules",
        title: "Idle and activity rules",
        content:
          "How long counts as idle, and which apps read as productive or distracting. These feed the score, so changing them changes how days are graded from that point on.",
        permission: "settings:view",
      },
      {
        route: "/settings/monitoring",
        title: "Everything is gated twice",
        content:
          "A feature has to be in your plan and switched on by the Owner. Turn monitoring off and the agent stops capturing — nothing is collected that you haven't enabled.",
        permission: "settings:view",
      },
    ],
  },
};

export function getTour(id: string): Tour | undefined {
  return TOURS[id];
}
